/**
 * Phase 6 — Notification Decision Engine Interfaces
 *
 * Defines the types flowing through the decision pipeline:
 *   RecommendationContext → DeliveryPlan → QueuedNotification
 */

import type {
  NotificationChannel,
  NotificationPriority,
  DeliveryDecision,
} from '../enums/notification.enums';

// ── Input to the decision engine ────────────────────────────────────────────

export interface RecommendationContext {
  userId: string;
  jobId: string;
  /** Overall match score 0–100 */
  matchScore: number;
  /** Job posting application deadline (if known) */
  deadline?: Date;
  /** Whether the user is explicitly tracking the company */
  isCompanyTracked: boolean;
  /** User's configured tracking priority for this company (1=HIGH, 2=MEDIUM, 3=LOW) */
  companyTrackingPriority?: 'HIGH' | 'MEDIUM' | 'LOW';
  /** Recommendation already created and committed to DB */
  recommendationId: string;
}

// ── Guard check results ──────────────────────────────────────────────────────

export interface DecisionGuardResult {
  passed: boolean;
  /** Human-readable reason for blocking (populated only if passed=false) */
  reason?: string;
}

// ── Output of the decision engine ───────────────────────────────────────────

export interface NotificationDeliveryPlan {
  userId: string;
  jobId: string;
  recommendationId: string;
  decision: DeliveryDecision;
  /** Channels to use for INSTANT delivery (empty for DIGEST/SKIP) */
  channels: NotificationChannel[];
  priority: NotificationPriority;
  /** ISO string title generated by the engine */
  title: string;
  message: string;
  /** Populated for INSTANT deliveries that land inside quiet hours */
  scheduledFor?: Date | undefined;
}

// ── Job data stored in BullMQ ────────────────────────────────────────────────

export interface NotificationJobData {
  notificationId: string;
  userId: string;
  jobId?: string;
  channel: NotificationChannel;
  priority: NotificationPriority;
  title: string;
  message: string;
  recipient: string;
  actionUrl?: string;
  attempt?: number;
}

export interface DigestJobData {
  userId: string;
  digestType: 'DAILY' | 'WEEKLY';
  /** ISO date string - the digest period start */
  periodStart: string;
}
