import { Injectable } from '@nestjs/common';

import { MetricCategory } from '../dto/product-intelligence.dto';

export interface DefinedMetric {
  code: string;
  name: string;
  category: MetricCategory;
  description: string;
  formula: string;
  dataSource: string;
  timeWindow: 'DAILY' | 'WEEKLY' | 'MONTHLY';
  targetValue: number;
  warningThreshold: number;
  unit: 'PERCENTAGE' | 'COUNT' | 'RATIO' | 'MILLISECONDS' | 'CURRENCY';
  currentValue: number;
  status: 'HEALTHY' | 'WARNING' | 'CRITICAL';
}

@Injectable()
export class MetricsRegistryService {
  getStandardMetrics(): DefinedMetric[] {
    return [
      {
        code: 'METRIC_ACQ_SIGNUP_VELOCITY',
        name: 'Weekly Signup Velocity',
        category: MetricCategory.ACQUISITION,
        description: 'Number of unique validated student accounts registered per rolling 7 days.',
        formula: 'COUNT(users WHERE createdAt >= now() - 7d AND isEmailVerified = true)',
        dataSource: 'users table',
        timeWindow: 'WEEKLY',
        targetValue: 50,
        warningThreshold: 20,
        unit: 'COUNT',
        currentValue: 64,
        status: 'HEALTHY',
      },
      {
        code: 'METRIC_ACT_FULL_ACTIVATION_RATE',
        name: 'Core Activation Rate',
        category: MetricCategory.ACTIVATION,
        description:
          'Percentage of signups who complete profile and track their first internship application within 7 days.',
        formula: '(COUNT(activated_users) / COUNT(total_signups)) * 100',
        dataSource: 'user_behavior_events & applications table',
        timeWindow: 'WEEKLY',
        targetValue: 60.0,
        warningThreshold: 45.0,
        unit: 'PERCENTAGE',
        currentValue: 68.5,
        status: 'HEALTHY',
      },
      {
        code: 'METRIC_ENG_DAU_MAU_STICKINESS',
        name: 'Product Stickiness (DAU/MAU)',
        category: MetricCategory.ENGAGEMENT,
        description:
          'Ratio of daily active users to monthly active users, measuring candidate reliance.',
        formula: '(DAU / MAU) * 100',
        dataSource: 'user_behavior_events',
        timeWindow: 'DAILY',
        targetValue: 40.0,
        warningThreshold: 25.0,
        unit: 'PERCENTAGE',
        currentValue: 49.4,
        status: 'HEALTHY',
      },
      {
        code: 'METRIC_RET_W1_RETENTION',
        name: 'Week 1 Retention Rate',
        category: MetricCategory.RETENTION,
        description:
          'Percentage of activated users who return and perform at least one career action 7 days after signup.',
        formula: '(Users active in Day 7-14 / Users signed up in Cohort) * 100',
        dataSource: 'user_behavior_events & career_events',
        timeWindow: 'WEEKLY',
        targetValue: 55.0,
        warningThreshold: 40.0,
        unit: 'PERCENTAGE',
        currentValue: 62.1,
        status: 'HEALTHY',
      },
      {
        code: 'METRIC_REV_MONTHLY_RECURRING',
        name: 'Monthly Recurring Revenue (MRR)',
        category: MetricCategory.REVENUE,
        description:
          'Predictable monthly revenue generated by active PRO and Institutional subscriptions.',
        formula: 'SUM(active_subscriptions * monthly_price)',
        dataSource: 'subscriptions & billing_invoices',
        timeWindow: 'MONTHLY',
        targetValue: 1200,
        warningThreshold: 500,
        unit: 'CURRENCY',
        currentValue: 1680,
        status: 'HEALTHY',
      },
      {
        code: 'METRIC_AI_FIRST_PASS_SATISFACTION',
        name: 'AI Response Satisfaction Score',
        category: MetricCategory.AI_QUALITY,
        description:
          'Average candidate star rating and helpfulness thumbs given to Copilot and Simulation answers.',
        formula: 'AVG(ratings WHERE type = "AI_QUALITY")',
        dataSource: 'user_feedbacks & ai_telemetry',
        timeWindow: 'WEEKLY',
        targetValue: 4.5,
        warningThreshold: 4.0,
        unit: 'RATIO',
        currentValue: 4.8,
        status: 'HEALTHY',
      },
      {
        code: 'METRIC_SUP_RESOLUTION_TIME',
        name: 'Support First-Contact Resolution SLA',
        category: MetricCategory.SUPPORT,
        description: 'Average hours to resolve user technical and billing support tickets.',
        formula: 'AVG(resolvedAt - createdAt WHERE status = "RESOLVED")',
        dataSource: 'support_tickets table',
        timeWindow: 'WEEKLY',
        targetValue: 4.0,
        warningThreshold: 12.0,
        unit: 'COUNT',
        currentValue: 2.1,
        status: 'HEALTHY',
      },
    ];
  }
}
